# Generated by Django 6.0.2 on 2026-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('overview', models.TextField(blank=True, default='')),
                ('vote_average', models.FloatField(default=0.0)),
                ('poster_path', models.CharField(blank=True, default='', max_length=500)),
                ('provider', models.CharField(choices=[('netflix', 'Netflix'), ('amazon', 'Amazon Prime Video'), ('apple', 'Apple TV+'), ('manual', 'Ajout manuel')], default='manual', max_length=20)),
                ('watched', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
